---
name: muehlbachler-public-services-cluster-applications
description: "Personal Public Services: Applications running on the Kubernetes public-services-cluster"
visibility: public
protected: true
topics:
  - services
  - kubernetes
  - gitops
  - fluxcd

rulesets:
  branch:
    enabled: false

accessPermissions:
  vault:
    enabled: false
